from . import fleet_vehicle
from . import fleet_vehicle_state
from . import fleet_vehicle_document
from . import fleet_vehicle_equipment
from . import product_template
from . import fleet_service_type
from . import fleet_vehicle_odometer
from . import purchase_order
from . import sale_order
from . import menu_force
from . import account_move
from . import leasing_contract
from . import account_payment