{
    'name': 'Fleet Custom Vehicle Management',
    'version': '1.0.0',
    'summary': 'Personnalisation flotte véhicules',
    'category': 'Human Resources/Fleet',
    'author': 'Custom',
    'depends': ['fleet', 'contacts', 'mail', 'purchase', 'product', 'sale', 'account', 'fleet_rental'],
    'data': [
        'security/ir.model.access.csv',
        'views/fleet_vehicle_views.xml',
        'views/leasing_menu_views.xml',
        'views/purchase_order_views.xml',
        'views/product_template_views.xml',
        'views/sell_order_views.xml',
        'views/fleet_vehicle_document_views.xml',
        'views/fleet_service_type_views.xml',
        'views/fleet_service_menu_views.xml',
        'views/fleet_service_log_views.xml',
        'views/fleet_vehicle_odometer_views.xml',
        'views/purchase_document_interfaces_views.xml',
        'views/fleet_vehicle_equipment_views.xml',
        'views/purchase_procurement_menu_views.xml',
        'views/purchase_order_leasing_views.xml',
        'data/leasing_cron.xml',
        'views/account_move_vendor_bill_views.xml',
        'views/account_payment_views.xml',
        'views/report_payment_order.xml',
        'data/account_move_sequence.xml',
        'data/account_payment_sequence.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'cargo_fleet/static/src/css/custom.css',
            'cargo_fleet/static/src/css/hide_upload.css',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}